# Fichier de configuration jekyll
author :
  name : Laurent Cottereau
  email : laurent@cottereau.name
  avatar : /img/avatar/09.jpg
  openid : http://lcottereau.pip.verisignlabs.com
  openidserver : http://pip.verisignlabs.com/server
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      theme: main
exclude: [ LICENSE, README.md, vendor ]
feed:
  path: feed/recent
gems:
  - jekyll-feed
  - jekyll-redirect-from
include: [ .htaccess ]
locale: fr
permalink: /blog/:year/:month/:day/:title/
timezone: Europe/Paris
title : Clarky's Corner
url: "http://laurent.cottereau.name"
